"""
        Rock Paper Scissors Game (python 3.12.5)
"""
import sys
from pyfiglet import Figlet
from random2 import choice
from colorama import init, Fore, Style

init()


game_menu = ["rock", "paper", "scissor"]


def generate_random_computer_choice():
    """
    this definition helps to select random word from game menu  "rock", "paper", "scissor"
    :return:random choice selected by computer
    """
    computer_choice = choice(game_menu)
    print(Fore.BLUE, "Computer Choice :", computer_choice, Style.RESET_ALL)
    return computer_choice


def take_user_input():
    """
    This asks the input choice to user and validates it against the games correct choices
    This do not allow to enter number, special char, _ etc.
    :return: prints error if user enters invalid input.
    """
    while True:
        user_choice = input("Enter your choice: ").strip()

        if user_choice == 'q':
            print("exiting the game....")
            sys.exit(0)

        elif user_choice == "" or '_' in user_choice:
            print("Invalid input, with underscore or empty input")
            break
        elif not user_choice.isalnum():
            print("Special char not allowed")
            break
        else:
            if user_choice.isalpha():
                user_choice.lower()
                user_choice_validated = [el for el in game_menu if el == user_choice]
                if user_choice_validated:
                    #print("You entered valid choice:", user_choice_validated[0])
                    return user_choice_validated[0]
                elif user_choice.isalpha():
                    print("Invalid word not allowed. Please enter one of the from 'rock' , 'scissor'. 'paper' : ")
                    break
                elif user_choice.isnumeric():
                    print("Invalid input, Numbers not allowed. Please enter one of the from 'rock' , 'scissor'. 'paper' : ")
                    break
            else:
                print("Invalid input, Numbers, special char must not be added with input. Please enter one of the from 'rock' , 'scissor'. 'paper' ")


def start_game():
    """
    Prints Game info at the start of the game.
    :return: string to describe game
    """
    game_info = """
    Welcome to Rock, Paper, Scissors Game! 
    Rock paper scissors is often used as a fair choosing method between two people, similar to coin flipping, drawing \n
    straws, or throwing dice in order to settle a dispute or make an unbiased group decision. Unlike truly random \n
    selection methods, however, rock paper scissors can be played with some degree of skill by recognizing \n
    and exploiting non-random behavior in opponents.
    
    It’s a game for two players where each player simultaneously forms one of three shapes with their hand:

    Rock: A fist.
    Paper: An open hand.
    Scissors: A fist with the index and middle fingers extended, forming a V.
    
    #Rules
    Rock crushes Scissors (Rock wins).
    Scissors cuts Paper (Scissors wins).
    Paper covers Rock (Paper wins).
    If both players choose the same shape, the game is a draw, and they can play again.
                     *** 
    Here you will play against Computer :) Ready ?
    ----------------------------------------------------------------------------------------
    """
    figlet = Figlet(font='slant')
    text_art = figlet.renderText('Rock Paper Scissor')
    print("\t \t \t",text_art)
    print(Fore.BLUE, "\t\t", game_info, Style.RESET_ALL)



# IMPROVE: optimize below logic to minimize comparisons
def get_results(user_choice: str, computer_choice: str):
    """
     This helps decide the results by comparing inputs as user choice and computer choice
    :param user_choice: input by user
    :param computer_choice: random choice generated by computer
    :return: prints the message what the output of game based predefines conditions
    """

    if user_choice == "rock" and computer_choice == "scissor":
        print(Fore.GREEN, f"You beat computer. Right Decision to select {user_choice}!", Style.RESET_ALL)
    elif user_choice == "scissor" and computer_choice == "rock":
        print(Fore.RED, f"Your decision was incorrect to choose {user_choice}, You lost, Computer won!", Style.RESET_ALL)
    elif user_choice == "scissor" and computer_choice == "paper":
        print(Fore.GREEN,f"You beat computer.Your decision right to choose {user_choice}", Style.RESET_ALL)
    elif user_choice == "paper" and computer_choice == "scissor":
        print(Fore.RED, f"Your decision was incorrect to choose {user_choice}, You lost, Computer won!", Style.RESET_ALL)
    elif user_choice == "paper" and computer_choice == "rock":
        print(Fore.GREEN, f"You beat computer. Your decision was right to choose {user_choice}", Style.RESET_ALL)
    elif user_choice == "rock" and computer_choice == "paper":
        print(Fore.RED, f"Your decision was incorrect to choose {user_choice}, You lost, Computer won!", Style.RESET_ALL)
    elif user_choice == computer_choice:
        print(Fore.RED, "Game Draw" , Style.RESET_ALL)
    else:
        print(Fore.RED, "Please continue playing again !!", Style.RESET_ALL)


def rock_paper_scissors_game():
    """
    This initiates the game and class all required definitions
    :return: None
    """
    start_game()

    while True:
        user_choice = take_user_input()

        computer_choice = generate_random_computer_choice()

        get_results(user_choice, computer_choice)

        continue


if __name__ == "__main__":
    rock_paper_scissors_game()
